###节点质量评估--Ising模型

##最新版本-边的关系是相关性

In [1]:
import numpy as np
import pandas as pd

def process_episode_data(episode_number):
    # 构建文件路径
    edges_data_path = f"D:/研究生论文/小论文2/代码/03网络图/02节点之间关系/桃花马上请长缨RAG/correlation_results_episode_{episode_number}.xlsx"
    node_state_data_path = f"D:/研究生论文/小论文2/代码/04质量评估_Ising模型/00节点状态/桃花马上请长缨RAG/node_state_episode_{episode_number}.xlsx"
    energy_data_output_path = f"D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/01节点质量/桃花马上请长缨RAG/node_energy_episode_{episode_number}.xlsx"
    
    # 第一步：根据网络边数据构建邻接矩阵
    edges_data = pd.read_excel(edges_data_path)
    nodes = set(edges_data['source']).union(set(edges_data['target']))
    n_nodes = len(nodes)
    adj_matrix = np.zeros((n_nodes, n_nodes))
    node_to_idx = {node: i for i, node in enumerate(nodes)}
    
    for _, edge in edges_data.iterrows():
        source = edge['source']
        target = edge['target']
        weight = edge['correlation']
        source_idx = node_to_idx[source]
        target_idx = node_to_idx[target]
        adj_matrix[source_idx, target_idx] = weight
        adj_matrix[target_idx, source_idx] = weight
    
    node_names = list(nodes)
    
    # 第二步：获取邻接矩阵对应节点状态
    node_state_data = pd.read_excel(node_state_data_path)
    node_state_map = dict(zip(node_state_data['Merged_Features'], node_state_data['Node state']))
    node_states = [node_state_map[node] for node in node_names]
    
    # 第三步：根据哈密顿函数计算节点能量（质量）
    node_energies = []
    for i in range(n_nodes):
        node_energy = 0
        for j in range(n_nodes):
            if i != j:
                node_energy += adj_matrix[i, j] * node_states[j]
        node_energy *= -node_states[i]
        node_energies.append(node_energy)
    
    # 第四步：保存到excel中
    energy_df = pd.DataFrame({'Node Name': node_names, 'Node Energy': node_energies})
    energy_df.to_excel(energy_data_output_path, index=False)
    print(f"节点能量已保存到文件: {energy_data_output_path}")

# 循环处理从第1集到第10集的数据
for episode_number in range(1, 92):
    print(f"正在处理第{episode_number}集数据...")
    process_episode_data(episode_number)


正在处理第1集数据...
节点能量已保存到文件: D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/01节点质量/桃花马上请长缨RAG/node_energy_episode_1.xlsx
正在处理第2集数据...
节点能量已保存到文件: D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/01节点质量/桃花马上请长缨RAG/node_energy_episode_2.xlsx
正在处理第3集数据...
节点能量已保存到文件: D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/01节点质量/桃花马上请长缨RAG/node_energy_episode_3.xlsx
正在处理第4集数据...
节点能量已保存到文件: D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/01节点质量/桃花马上请长缨RAG/node_energy_episode_4.xlsx
正在处理第5集数据...
节点能量已保存到文件: D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/01节点质量/桃花马上请长缨RAG/node_energy_episode_5.xlsx
正在处理第6集数据...
节点能量已保存到文件: D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/01节点质量/桃花马上请长缨RAG/node_energy_episode_6.xlsx
正在处理第7集数据...
节点能量已保存到文件: D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/01节点质量/桃花马上请长缨RAG/node_energy_episode_7.xlsx
正在处理第8集数据...
节点能量已保存到文件: D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/01节点质量/桃花马上请长缨RAG/node_energy_episode_8.xlsx
正在处理第9集数据...
节点能量已保存到文件: D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/01节点质量/桃花马上请长缨RAG/node_energy_episode_9.xlsx
正在处理第10集数据...
节点能量已

###之前版本-边的关系是权重-共线得到

In [3]:
import numpy as np
import pandas as pd

def process_episode_data(episode_number):
    # 构建文件路径
    edges_data_path = f"D:/研究生论文/小论文2/代码/03网络图/01网络图构建/边数据/天宝伏妖录/network_edges_episode_{episode_number}.xlsx"
    node_state_data_path = f"D:/研究生论文/小论文2/代码/04质量评估_Ising模型/00节点状态/天宝伏妖录/node_state_episode_{episode_number}.xlsx"
    energy_data_output_path = f"D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/01节点质量/天宝伏妖录/node_energy_episode_{episode_number}.xlsx"
    
    # 第一步：根据网络边数据构建邻接矩阵
    edges_data = pd.read_excel(edges_data_path)
    nodes = set(edges_data['source']).union(set(edges_data['target']))
    n_nodes = len(nodes)
    adj_matrix = np.zeros((n_nodes, n_nodes))
    node_to_idx = {node: i for i, node in enumerate(nodes)}
    
    for _, edge in edges_data.iterrows():
        source = edge['source']
        target = edge['target']
        weight = edge['weight']
        source_idx = node_to_idx[source]
        target_idx = node_to_idx[target]
        adj_matrix[source_idx, target_idx] = weight
        adj_matrix[target_idx, source_idx] = weight
    
    node_names = list(nodes)
    
    # 第二步：获取邻接矩阵对应节点状态
    node_state_data = pd.read_excel(node_state_data_path)
    node_state_map = dict(zip(node_state_data['Merged_Features'], node_state_data['Node state']))
    node_states = [node_state_map[node] for node in node_names]
    
    # 第三步：根据哈密顿函数计算节点能量（质量）
    node_energies = []
    for i in range(n_nodes):
        node_energy = 0
        for j in range(n_nodes):
            if i != j:
                node_energy += adj_matrix[i, j] * node_states[j]
        node_energy *= -node_states[i]
        node_energies.append(node_energy)
    
    # 第四步：保存到excel中
    energy_df = pd.DataFrame({'Node Name': node_names, 'Node Energy': node_energies})
    energy_df.to_excel(energy_data_output_path, index=False)
    print(f"节点能量已保存到文件: {energy_data_output_path}")

# 循环处理从第1集到第10集的数据
for episode_number in range(1, 14):
    print(f"正在处理第{episode_number}集数据...")
    process_episode_data(episode_number)


正在处理第1集数据...
节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/01节点质量/天宝伏妖录/node_energy_episode_1.xlsx
正在处理第2集数据...
节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/01节点质量/天宝伏妖录/node_energy_episode_2.xlsx
正在处理第3集数据...
节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/01节点质量/天宝伏妖录/node_energy_episode_3.xlsx
正在处理第4集数据...
节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/01节点质量/天宝伏妖录/node_energy_episode_4.xlsx
正在处理第5集数据...
节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/01节点质量/天宝伏妖录/node_energy_episode_5.xlsx
正在处理第6集数据...
节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/01节点质量/天宝伏妖录/node_energy_episode_6.xlsx
正在处理第7集数据...
节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/01节点质量/天宝伏妖录/node_energy_episode_7.xlsx
正在处理第8集数据...
节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/01节点质量/天宝伏妖录/node_energy_episode_8.xlsx
正在处理第9集数据...
节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/01节点质量/天宝伏妖录/node_energy_episode_9.xlsx
正在处理第10集数据...
节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/01节点质量/天宝伏妖录/node_energy_episode_10.xlsx
正在处理第11集数据...
节点能量已保存到文件: E:/桌面/代码/04质

###单集节点能量计算--下面不用，是上面最终代码的推导过程

In [8]:
import pandas as pd
import numpy as np

###第一步：根据网络边数据构建邻接矩阵

# 1. 读取边数据文件
edges_data = pd.read_excel("D:/研究生论文/小论文2/代码/03网络图/01网络图构建/边数据/百妖谱/network_edges_episode_1.xlsx")


# 2. 获取所有节点
nodes = set(edges_data['source']).union(set(edges_data['target']))

# 3. 创建一个空的邻接矩阵
n_nodes = len(nodes)
adj_matrix = np.zeros((n_nodes, n_nodes))

# 4. 创建节点索引映射
node_to_idx = {node: i for i, node in enumerate(nodes)}

# 5. 遍历边数据，填充邻接矩阵
for _, edge in edges_data.iterrows():
    source = edge['source']
    target = edge['target']
    weight = edge['weight']
    
    source_idx = node_to_idx[source]
    target_idx = node_to_idx[target]
    
    # 更新邻接矩阵
    adj_matrix[source_idx, target_idx] = weight
    adj_matrix[target_idx, source_idx] = weight  # 对称填充

# 6. 创建节点名称列表
node_names = list(nodes)


###第二步：获取邻接矩阵对应节点状态


# 读取节点状态数据
node_state_data = pd.read_excel("D:/研究生论文/小论文2/代码/04质量评估_Ising模型/00节点状态/百妖谱/node_state_episode_1.xlsx")

# 创建节点状态映射字典
node_state_map = dict(zip(node_state_data['Merged_Features'], node_state_data['Node state']))

# 按照邻接矩阵中节点的顺序提取节点的状态
node_states = [node_state_map[node] for node in node_names]



###第三步：根据哈密顿函数计算节点能量（质量）


# 1. 初始化节点能量列表
node_energies = []

# 2. 遍历每个节点
for i in range(n_nodes):
    node_energy = 0
    
    # 3. 计算节点 i 的能量
    for j in range(n_nodes):
        if i != j:  # 排除自身节点
            node_energy += adj_matrix[i, j] * node_states[j]  # 邻接矩阵中的权重 * 邻居节点的状态
    node_energy *= -node_states[i]  # 乘以节点的状态
    node_energies.append(node_energy)

# 打印节点能量
for i, energy in enumerate(node_energies):
    print(f"节点 {node_names[i]} 的能量：{energy}")

###第四步：保存到excel中

# 创建 DataFrame，包含节点名称和节点能量
energy_df = pd.DataFrame({'Node Name': node_names, 'Node Energy': node_energies})

# 保存 DataFrame 到 Excel 文件
energy_file_path = "D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/百妖谱/node_energy_episode_1.xlsx"
energy_df.to_excel(energy_file_path, index=False)

print("节点能量已保存到文件:", energy_file_path)


节点 艺术风格 的能量：-36.0
节点 画面质量 的能量：-8.0
节点 主题 的能量：36.0
节点 剧情 的能量：232.0
节点 文化和情境契合度 的能量：-6.0
节点 整体适应性与创新性 的能量：-48.0
节点 声音设计 的能量：92.0
节点 人物 的能量：78.0
节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/百妖谱/node_energy_episode_1.xlsx


###邻接矩阵+节点状态

In [4]:
import pandas as pd
import numpy as np

# 1. 读取边数据文件
edges_data = pd.read_excel("D:/研究生论文/小论文2/代码/03网络图/01网络图构建/边数据/百妖谱/network_edges_episode_1.xlsx")


# 2. 获取所有节点
nodes = set(edges_data['source']).union(set(edges_data['target']))

# 3. 创建一个空的邻接矩阵
n_nodes = len(nodes)
adj_matrix = np.zeros((n_nodes, n_nodes))

# 4. 创建节点索引映射
node_to_idx = {node: i for i, node in enumerate(nodes)}

# 5. 遍历边数据，填充邻接矩阵
for _, edge in edges_data.iterrows():
    source = edge['source']
    target = edge['target']
    weight = edge['weight']
    
    source_idx = node_to_idx[source]
    target_idx = node_to_idx[target]
    
    # 更新邻接矩阵
    adj_matrix[source_idx, target_idx] = weight
    adj_matrix[target_idx, source_idx] = weight  # 对称填充

# 6. 创建节点名称列表
node_names = list(nodes)



# 读取节点状态数据
node_state_data = pd.read_excel("D:/研究生论文/小论文2/代码/04质量评估_Ising模型/00节点状态/百妖谱/node_state_episode_1.xlsx")

# 创建节点状态映射字典
node_state_map = dict(zip(node_state_data['Merged_Features'], node_state_data['Node state']))

# 按照邻接矩阵中节点的顺序提取节点的状态
node_states = [node_state_map[node] for node in node_names]


# 打印节点名称与邻接矩阵
print("节点名称：", node_names)
# 打印节点的状态
print("节点状态：", node_states)
print("邻接矩阵：")
print(adj_matrix)


节点名称： ['艺术风格', '画面质量', '主题', '剧情', '文化和情境契合度', '整体适应性与创新性', '声音设计', '人物']
节点状态： [1, 1, 1, -1, 1, 1, -1, 1]
邻接矩阵：
[[  0.  18.   0.   0.   0.  18.   0.   0.]
 [ 18.   0.   4.   0.   0.  50.  64.   0.]
 [  0.   4.   0.  66.   2.   4.   0.  20.]
 [  0.   0.  66.   0.   0.  34.   0. 132.]
 [  0.   0.   2.   0.   0.   4.   0.   0.]
 [ 18.  50.   4.  34.   4.   0.  28.  34.]
 [  0.  64.   0.   0.   0.  28.   0.   0.]
 [  0.   0.  20. 132.   0.  34.   0.   0.]]


###哈密顿函数计算节点能量

In [5]:
# 1. 初始化节点能量列表
node_energies = []

# 2. 遍历每个节点
for i in range(n_nodes):
    node_energy = 0
    
    # 3. 计算节点 i 的能量
    for j in range(n_nodes):
        if i != j:  # 排除自身节点
            node_energy += adj_matrix[i, j] * node_states[j]  # 邻接矩阵中的权重 * 邻居节点的状态
    node_energy *= -node_states[i]  # 乘以节点的状态
    node_energies.append(node_energy)

# 打印节点能量
for i, energy in enumerate(node_energies):
    print(f"节点 {node_names[i]} 的能量：{energy}")


节点 艺术风格 的能量：-36.0
节点 画面质量 的能量：-8.0
节点 主题 的能量：36.0
节点 剧情 的能量：232.0
节点 文化和情境契合度 的能量：-6.0
节点 整体适应性与创新性 的能量：-48.0
节点 声音设计 的能量：92.0
节点 人物 的能量：78.0


###存储到excel中

In [7]:
import pandas as pd

# 创建 DataFrame，包含节点名称和节点能量
energy_df = pd.DataFrame({'Node Name': node_names, 'Node Energy': node_energies})

# 保存 DataFrame 到 Excel 文件
energy_file_path = "D:/研究生论文/小论文2/代码/04质量评估_Ising模型/01质量评估/百妖谱/node_energy_episode_1.xlsx"
energy_df.to_excel(energy_file_path, index=False)

print("节点能量已保存到文件:", energy_file_path)


节点能量已保存到文件: E:/桌面/代码/04质量评估_Ising模型/01质量评估/百妖谱/node_energy_episode_1.xlsx
